---

Style/Copyright:
  Description: 'Include a copyright notice in each file before any code.'
  Enabled: false

# Enabled by default
Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/DocumentationMethod:
  Description: 'Public methods.'
  Enabled: false
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Lint/IneffectiveAccessModifier:
  Description: >-
                 Checks for attempts to use `private` or `protected` to set
                 the visibility of a class method, which does not work.
  Enabled: false

Style/ImplicitRuntimeError:
  Description: >-
                 Use `raise` or `fail` with an explicit exception class and
                 message, rather than just a message.
  Enabled: false

Style/InlineComment:
  Description: 'Avoid trailing inline comments.'
  Enabled: false

Style/MissingElse:
  Description: >-
                Require if/case expressions to have an else branches.
                If enabled, it is recommended that
                Style/UnlessElse and Style/EmptyElse be enabled.
                This will conflict with Style/EmptyElse if
                Style/EmptyElse is configured to style "both"
  Enabled: false
  EnforcedStyle: both
  SupportedStyles:
    # if - warn when an if expression is missing an else branch
    # case - warn when a case expression is misisng an else branch
    # both - warn when an if or case expression is missing an else branch
    - if
    - case
    - both

Style/MethodCallWithArgsParentheses:
  Description: 'Use parentheses for method calls with arguments.'
  StyleGuide: '#method-invocation-parens'
  Enabled: false

Style/MultilineAssignmentLayout:
  Description: 'Check for a newline after the assignment operator in multi-line assignments.'
  StyleGuide: '#indent-conditional-assignment'
  Enabled: false

# Enabled by default, but we shouldn't enforce names; leave it up to the user
Style/SingleLineBlockParams:
  Description: 'Enforces the names of some block params.'
  Enabled: false

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  StyleGuide: '#percent-i'
  Enabled: false

# Enabled by default, but it messes with stuff
Style/TrailingUnderscoreVariable:
  Description: >-
                 Checks for the usage of unneeded trailing underscores at the
                 end of parallel variable assignment.
  Enabled: false

# Too rails specific
Rails/Delegate:
  Description: 'Prefer delegate method for delegations.'
  Enabled: false

# We actually do `exit` a bunch with scripts
Rails/Exit:
  Description: >-
                  Favor `fail`, `break`, `return`, etc. over `exit` in
                  application or library code outside of Rake files to avoid
                  exits during unit testing or running in production.
  Enabled: false


# Enabled by default but doesn't work with our rack-test
Rails/HttpPositionalArguments:
  Description: 'Use keyword arguments instead of positional arguments in http method calls.'
  Enabled: false
  Include:
    - 'spec/**/*'
    - 'test/**/*'

# Enabled by default, but super chatty and it's not useful with activesupport
Rails/TimeZone:
  Description: 'Checks the correct usage of time zone aware methods.'
  StyleGuide: 'https://github.com/bbatsov/rails-style-guide#time'
  Reference: 'http://danilenko.org/2012/7/6/rails_timezones'
  Enabled: false

# Enabled by default, but we use `private` for more than syntactic significance and this got in the way of that.
# TODO: See if recent changes mean we can re-enable this for our scenario
Lint/UselessAccessModifier:
  Description: 'Checks for useless access modifiers.'
  Enabled: false
  ContextCreatingMethods: []
  MethodCreatingMethods: []
